backend/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from accounts.views import sign_up_view, login_view

from accounts.forms import PasswordResetCustomForm, PasswordResetConfirmForm
from .views import (
    home_view,
    contact_view,
    about_view,
    product_registration_view,
    products,
    product_view,
    profile_view,
    courses_view,
    find_your_employee_view,
    edit_profile_view,
    search_view,
    category_search_view,
    plan_view,

)

urlpatterns = [
    path('', home_view, name='home'),
    path('contact-us/', contact_view, name='contact'),
    path('about-us/', about_view, name='about'),
    path('courses/', courses_view, name='course'),
    path('plan/', plan_view, name='plan'),
    path('query/', search_view, name='search'),
    path('products/', products, name='products'),
    path('category/<str:category>', category_search_view, name='category_search'),
    path('product-registration/', product_registration_view,
         name='product-registration'),
    path('find-your-employer/', find_your_employee_view, name='find-your-employer'),


    path('product/<str:pk>/', product_view, name='product'),
    path('profile/<str:username>/', profile_view, name='profile'),
    path('profile/edit/<str:username>', edit_profile_view, name='edit-profile'),



    path('signup/', sign_up_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.
         as_view(template_name='core/account/password_reset_form.html',
                 form_class=PasswordResetCustomForm), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.
         as_view(template_name='core/account/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.
         as_view(template_name='core/account/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.
         as_view(template_name='core/account/password_reset_confirm.html',
                 form_class=PasswordResetConfirmForm), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.
         as_view(template_name='core/account/password_reset_complete.html'),
         name='password_reset_complete'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django_countries.fields import CountryField
import uuid


DELIVER = (
    ('', 'Do you Deliver?'),
    ('Y', 'Yes'),
    ('N', 'No'),
)
PLAN_OPTION = (
    ('Mwaiseni - FREE', 'Mwaiseni'),
    ('Kadyonko - K2/DAY', 'Kadyonko'),
    ('Mukolwe - K15/Month', 'Mukolwe'),
)

IS_SERVICE = (
    ('', 'Product or Service'),
    ('Product', 'Product'),
    ('Service', 'Service '),
    ('Both', 'Both '),
)


class Plan(models.Model):
    name = models.CharField(
        max_length=50, choices=PLAN_OPTION, default='Mwaiseni - FREE')
    price = models.PositiveIntegerField(null=True, blank=True)
    description = models.TextField(null=True, blank=True, max_length=1000)

    def __str__(self):
        return str(self.name)


class Profile(models.Model):
    user_uuid = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(
        max_length=50, help_text='Must have a country code', null=True, blank=True)
    country = CountryField(null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    business_name = models.CharField(max_length=100, null=True, blank=True)
    business_location = models.CharField(max_length=50, null=True, blank=True)
    deliver = models.CharField(
        max_length=20, choices=DELIVER, null=True, blank=True)
    plan = models.OneToOneField(
        Plan, on_delete=models.CASCADE, null=True, blank=True)
    bio = models.TextField(max_length=400, null=True,
                           blank=True, help_text='Maximum 300 Words')
    image = models.ImageField(
        upload_to='product', default='product/default.png')
    cover_image = models.ImageField(
        upload_to='cover', default='cover/default.jpg')
    is_seller = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user.username)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        width = 200
        height = 200

        if img.width > width or img.height > height:
            output = (width, height)
            img.thumbnail(output)
            img.save(self.image.path)


class Category(models.Model):
    CATEGORY_TYPE=(
        ("Food","Food"),
        ("Electronic", "Electronic"),
        ("Home Appreance", "Home Appreance"),
        ("Clothing", "Clothing"),
        ("Shoes", "Shoes"),
        ("Finance", "Finance"),
    )
    cat_type = models.CharField(max_length=50,choices=CATEGORY_TYPE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return str(self.name)


class Review(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.PROTECT)
    comment = models.TextField(max_length=200)
    rates = models.PositiveIntegerField(default=0)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return str(self.rates)


class Size(models.Model):
    SIZES=(
        ("S","Small"),
        ("M","Medium"),
        ("L","Large"),
    )
    name = models.CharField(max_length=30,choices=SIZES, unique=True)

    def __str__(self):
        return str(self.name)


class Product(models.Model):
    product_uuid = models.UUIDField(
        primary_key=True, blank=True, default=uuid.uuid4, editable=False)
    seller = models.ForeignKey(Profile, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    actual_price = models.CharField(max_length=15)
    previous_price = models.CharField(max_length=15, null=True, blank=True)
    description = models.TextField(max_length=300, null=True, blank=True)
    image = models.ImageField(upload_to='product')
    approved = models.BooleanField(default=False)
    top_sale = models.BooleanField(default=False)
    reviews = models.ForeignKey(
        Review, on_delete=models.CASCADE, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    product_type = models.CharField(max_length=20, choices=IS_SERVICE)
    size = models.ManyToManyField(Size, null=True, blank=True)

    def __str__(self):
        return str(self.name)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        width = 500
        height = 400
        if img.width > width or img.height > height:
            output = (width, height)
            img.thumbnail(output)
            img.save(self.image.path)

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.core.mail import send_mass_mail, send_mail


from .models import (
    Product,
    Profile,
    Category,
    Review,
    Plan,
)

from .forms import (
    ProductModelForm,
    UpdateProfileForm,
    CoverUpload,
    ContactForm,
    ReviewForm,
)


def home_view(request):
    if request.user.is_authenticated and request.user.profile.is_seller:
        return redirect('products')
    top_sale_products = Product.objects.filter(
        top_sale=True, approved=True)[:8]
    reviews = Review.objects.all()

    context = {
        'top_sale_products': top_sale_products,
        'reviews': reviews
    }

    return render(request, 'core/pages/index.html', context)


def about_view(request):
    return render(request, 'core/pages/about.html')


def contact_view(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            fullname = form.cleaned_data.get("fullname")
            email = form.cleaned_data.get("email")
            subject = form.cleaned_data.get("subject")
            message = form.cleaned_data.get("message")
            if len(fullname) > 6:

                send_mail(subject=subject,
                          message=message,
                          from_email=email,
                          recipient_list=['patrickckabwe@gmail.com'],
                          html_message=f"Full Name: {fullname} <br> From :{email} <br><br> Message : {message}"
                          )
                messages.success(
                    request, f'We have recieved your email, We will get in touch with you as soon as possible')
                return redirect('contact')
            else:
                messages.error(
                    request, f'Make sure you entered a full name e.g John Doe')
                return redirect('contact')
        else:
            messages.info(
                request, f'Check your input fields Make sure all fields are filled')
            return redirect('contact')
    else:
        form = ContactForm()
    context = {
        "form": form,
    }
    return render(request, 'core/pages/contact.html', context)


def products(request):
    approved_products = Product.objects.filter(approved=True)
    top_sale_products = Product.objects.filter(top_sale=True, approved=True)
    categories = Category.objects.all()

    context = {
        'approved_products': approved_products,
        'top_sale_products': top_sale_products,
        'categories': categories,
    }

    return render(request, 'core/pages/products.html', context)


def category_search_view(request, category):
    approved_products = Product.objects.filter(
        approved=True, category__name__iexact=category)
    categories = Category.objects.all()

    context = {
        'approved_products': approved_products,
        'categories': categories,
    }

    return render(request, 'core/pages/category_search.html', context)


def product_view(request, pk):
    product = get_object_or_404(Product, pk__iexact=pk)
    related_products = Product.objects.filter(
        category__name=product.category, approved=True).exclude(pk=pk)

    context = {
        'product': product,
        'related_products': related_products,
    }
    return render(request, 'core/pages/product.html', context)


@login_required(login_url='products')
def product_registration_view(request):
    """
    Checks to see if logged in user is a seller if so they will
    access the page

    This is so to prevent anyuser from adding products
    """

    if not request.user.profile.is_seller:
        return redirect('products')

    """
    Checks to see if logged in user has products < 1

    This is so to prevent user from adding products just after
    registration
    """
    if request.user.profile.product_set.all().count() < 1:
        return redirect('products')

    seller_auth = request.user
    products = Product.objects.filter(seller__user=seller_auth)
    categories = Category.objects.all()

    if request.method == 'POST':
        form = ProductModelForm(request.POST, request.FILES)
        if form.is_valid():
            if request.user.profile.is_seller:
                product_obj = form.save(commit=False)
                product_obj.seller = products[0].seller
                product_obj.save()
                messages.success(
                    request, f"You have Successfully Registered {form.cleaned_data.get('name')},Please Wait While we Check your {form.cleaned_data.get('product_type')}")
                return redirect('product-registration')
        else:
            messages.info(request, f"Check you inputs, File must be image")
            return redirect('product-registration')
    else:
        form = ProductModelForm()

    context = {
        'products': products,
        'seller_auth': seller_auth,
        'seller_auth': seller_auth,
        'form': form,
        'categories': categories,
    }

    return render(request, 'core/pages/product-registration.html', context)


def find_your_employee_view(request):
    context = {}
    return render(request, 'core/pages/find-your-employer.html', context)


def courses_view(request):
    context = {}
    return render(request, 'core/pages/courses.html', context)


def plan_view(request):
    plans = Plan.objects.all()
    # plan = Plan.objects.get(name=plan)
    context = {
        'plans': plans,
        # 'plan': plan,
    }
    return render(request, 'core/pages/plan.html', context)


def profile_view(request, username):
    seller = get_object_or_404(Profile, user__username__exact=username)

    if request.method == "POST":
        form = CoverUpload(request.POST, request.FILES)
        if form.is_valid():
            cover_image = form.cleaned_data.get('cover_image')
            profile = get_object_or_404(
                Profile, user__username__exact=username)
            profile.cover_image.delete()
            profile.cover_image = cover_image
            profile.save()
            messages.success(request, f'Successfully updated your Cover Image')
            return redirect('profile', seller.user.username)
        else:
            messages.info(request, f'Image must be less then 20mb')
            return redirect('profile', seller.user.username)
    else:
        form = CoverUpload()

    # Handle reviews via Ajax Call
    # if request.is_ajax():
    #     form_rate = ReviewForm()
    #     if form_rate.is_valid():
    #         pass
    # else:
    #     form_rate = ReviewForm()

    context = {
        'form': form,
        # 'form_rate': form_rate,
        'seller': seller,
    }
    return render(request, 'core/pages/profile.html', context)


@login_required(login_url='login')
def edit_profile_view(request, username):
    seller = get_object_or_404(Profile, user__username=username)
    if not request.user.profile.is_seller:
        return redirect('products')

    if request.method == 'POST':
        form = UpdateProfileForm(request.POST, request.FILES, instance=seller)
        if form.is_valid():
            form.save()
            messages.success(request, f'Successfully updated your profile')
            return redirect('profile', seller.user.username)
        else:
            messages.info(request, f'Please check your credentials')
    else:
        form = UpdateProfileForm(instance=seller)

    context = {
        'seller': seller,
        'form': form,
    }
    return render(request, 'core/pages/update-profile.html', context)


def search_view(request):

    try:
        q = request.GET.get('search')
        if q == '':
            return redirect('products')
        products = Product.objects.filter(
            Q(name__icontains=q) |
            Q(category__name__icontains=q)
        )
        approved_products = []
        for product in products:
            if product.approved:
                approved_products.append(product)
    except (ValueError, UnboundLocalError):
        approved_products = []

    context = {
        'products': approved_products,
        'products_returned': len(approved_products),
        'search_result': q
    }
    return render(request, 'core/pages/search-results.html', context)

templates/core/pages/about.html
{% extends 'core/base.html' %}
{% load static %}


{% block content %}

   <section>
      <div class="fye-section-register" style="background-color: var(--bg-clr);">
         <div class="container fye-section-two" style="align-items: stretch;">
            <div class="fye-section-right-one" style="max-width: 530px;">
               <h1 style="text-align: left;">ABOUT US</h1>
                <p style="font-size: 1rem;text-align: left;">
                    Enrich-Zm is a platform built by innovative Zambians who have the interest 
                    in helping other individual to keep thriving. 
                </p>
            
                <p style="font-size: 1rem;text-align: left;">
                    The many goal for this platform is to help individual who have businesses to
                    advertise there products | services, Tutors/Teachers to provide educative 
                    content that is benefitial to students and pupils as well as those looking for 
                    employment to post there skills and employers to find the best employees
                    that suite there requirements. 
                </p>

                <p style="font-size: 1rem; text-align: left;">
                    This initiative is focused on helping individuals and communities.
                </p>
            </div>

            <div class="fye-section-left-one">
               <div class="fye-form-inner-wrapper mt mb">
                  <p style="font-size: 1rem; color: var(--primary-clr) ;text-align: left;">
                     "The person who doesn't know where is next wealth is coming
                     from usually doesn't know where his last expenditure went."
                     <span style="font-weight: 500; margin-right: 1em; float: right; color: var(--line-clr); margin-top: .5em;">_Kazion</span> 
                  </p>
               </div>
             </div>
         </div>
      </div>
   </section>

   
   <!-- FOOTER -->
   <!-- <footer>
   <div class="last-footer">
      <span>Copyright&copy;2020 <a href="">KazionDesigns</a></span>
   </div>
   </footer> -->
   <!--END OF FOOTER -->
{% endblock %}

templates/core/pages/courses.html
{% extends 'core/base.html' %}
{% load static %}


{% block content %}

   <header>
      <div class="fye-header-wrapper" style="height: 94.6vh;">
         <div class="container fye-header">
               <div class="fye-left">
                  <h1>LEARN AT YOUR<br>OWN PACE</h1>
                  <!-- <a href="" class="btn secondary btn-sm mt-1">Sign up for free</a> -->

                    <h1 style="color: var(--bg-clr); margin-top: 30px; text-shadow: 0 0 6px black; color: var(--primary-clr);"> Coming Soon!! </h1>
                    <h3 style="color: var(--grey-d-clr);"> Stay Tuned </h3>
               </div>
               
               <div class="fye-right main-course-right">
                  <img src="{% static 'img/Mask6.svg' %}" alt="">
               </div>
         </div>
      </div>
   </header>

{% endblock %}

templates/core/pages/profile.html
{% extends 'core/base.html' %}
{% load static %}


{% block content %}

  <!-- Main Header -->

  <div class="profile-hero-section" 
  style="background: url('{{ seller.cover_image.url }}') no-repeat;background-attachment: fixed; background-position: center; background-size: cover;">
    <div class="cover_overlay">
      <div class="container profile-hero">
        
        <div class="seller-profile">
          <div class="user-profile-img">
            <img src="{{ seller.image.url }}" alt="">
          </div>
          <div class="seller-profile-header-details">
            
            {% if seller.business_name %}
            <h4>{{ seller.business_name}}</h4>
            {% else %}
            <h4>{{ seller.user.username}}</h4>
            {% endif %}
            <h4>{{ seller.user.email}}</h4>
          </div>
        </div>
        
        
        {% if request.user == seller.user %}
        <div class="profile-buttons" style="display: flex; gap: 10px;">
          <div class="button-profile-hero">
            <a href="" class="btn primary-outline btn-sm" id="cover_image">Upload cover image</a>
          </div>
          <div class="button-profile-hero">
            <!-- <a href="" class="btn primary btn-sm" id="plan_upgrade">Upgrade Plan</a> -->
          </div>
        </div>
         
        {% else %}
        <div class="profile-buttons" style="display: flex; gap: 10px;">
          <div class="button-profile-hero ">
            <a href="https://wa.me/{{ seller.phone }}" 
            class="btn primary-outline btn-sm" 
            id="whatsapp_connector" 
            target="_blank">
            Connect via WhatsApp  </a>
          </div>
        </div>
        {% endif %}
          
      
        <form method="POST" enctype="multipart/form-data" id="cover_image_form">{% csrf_token %}
          <label for="cover_img"></label>
          
          {{ form.cover_image }}
          <button type="submit"  class="btn primary btn-sm">Upload</button>
        </form>
        
      </div>
    </div>
    
  </div>


    <section >

      <div class="profile-filter">
        <div class="container tab-filter profile-filter-heading">
          <div><a href="{% url 'profile' seller.user.username %}"class="active">Profile </a></div>
          {% if request.user == seller.user and seller.user.profile.is_seller %}
            <div>
              <a href="{% url 'product-registration' %}">Add Products</a>
            </div>   
          {% endif %}
          
          <!-- <div><a href="">Reviews</a></div>
          <div><a href="">Followers</a></div> -->
        </div>
      </div>

      <div class="profile-details">
        <div class="container profile-details-section">

          <!-- PROFILE INFO -->
          <div class="profile-details-left">

            <!-- PROFILE -->

            <section class="our-profile">
              <div class="our-profile-header">
                <h2 class="profile-h2">Our Profile</h2>
              </div>
              <div class="our-profile-details">
                <p>
                  <span id="heads"> Location:</span> <span id="results">
                    {% if seller.business_location %}
                      {{ seller.business_location }} 
                    {% else %}
                      {% if seller.user == request.user and request.user.profile.count > 0 %}
                        <a href="{% url 'edit-profile' seller.user.username %}">Edit profile</a>
                      {% else %}
                        <span>No Location was found</span>
                      {% endif %}
                    {% endif %}
                  </span>
                </p>
                <p>
                  <span id="heads"> Business Name </span> : 
                  {% if seller.business_name %}
                    {{ seller.business_name }}
                    {{ seller.get_country_display }},
                    {{ seller.city.capitalize }} 
                  {% else %}

                    {% if seller.user == request.user and request.user.profile.count > 0 %}
                      <a href="{% url 'edit-profile' seller.user.username %}">Edit profile</a>
                    {% else %}
                      <span>No name</span>
                    {% endif %}
                  {% endif %}
                  </span>
                </p>
                <p>
                  <span id="heads"> Phone Number </span> : <span id="results"> 
                    {% if seller.phone %}
                      {{ seller.phone }} 
                    {% else %}
                      {% if seller.user == request.user and request.user.profile.count > 0 %}
                        <a href="{% url 'edit-profile' seller.user.username %}" title="Edit your Phone Number">Edit profile</a>
                      {% else %}
                        <span>No number</span>
                      {% endif %}
                    {% endif %}
                  </span>
                </p>
                <p><span id="heads"> Deliver</span> : <span id="results"> 
                  {% if seller.deliver %}
                  {{ seller.get_deliver_display }} 
                  {% else %}
                    {% if seller.user == request.user and request.user.profile.count > 0 %}
                      <a href="{% url 'edit-profile' seller.user.username %}" title="Edit your Delivery Status">Edit profile</a>
                    {% else %}
                      <span>No status added</span>
                    {% endif %}
                  {% endif %}
                  </span>
                </p>
              </div>

              {% if seller.user == request.user and request.user.profile.is_seller %}
                <div class="profile-footer-details">
                  <a href="{% url 'edit-profile' seller.user.username %}" class="btn primary btn-sm">Edit Profile</a>
                </div>
              {% else %}
                <!-- <div class="profile-footer-details">
                  <div class="rates_form">
                    <form method="POST" accept="profile" style="margin-top: 0; width: 100%;">
                      {% csrf_token %}
                      {{ form_rate.user }}
                      {{ form_rate.comment }}
                      {{ form_rate.rate }}
                      <div class="rate_ajax" style="margin: .5em 0;">
                        <a href=""><i class="far fa-star"></i></a>
                        <a href=""><i class="far fa-star"></i></a>
                        <a href=""><i class="far fa-star"></i></a>
                        <a href=""><i class="far fa-star"></i></a>
                        <a href=""><i class="far fa-star"></i></a>
                      </div>
                      <button type="submit" class="btn primary btn-sm">Add rate</button>
                    </form>
                  </div>
                </div> -->
                <!-- <div class="profile-footer-details">
                  <h5 style="margin-bottom:5px; color:red;">DO YOU WANT TO REGISTER AS A SELLER?</h5>
                  <a href="{% url 'edit-profile' seller.user.username %}" class="btn primary btn-sm">Contact us</a>
                </div> -->
              {% endif %}
                
            
            </section>

            <!--END OF PROFILE -->


              <!-- ABOUT US -->
              {% if seller.bio %}
                <section class="joined">
                
                  <div class="joined-header">
                    <h2 class="profile-h2">Our Bio</h2>
                  </div>
                
                  <p class="joined-details">
                    {{ seller.bio }}
                  </p>
                
                </section>
              {% endif %}

            <!-- JOINED -->
            <section class="joined">
              <div class="joined-header">
                <h2 class="profile-h2">Joined</h2>
              </div>
              <div class="joined-details">
                
                {% if seller.business_name %}
                  <p>{{ seller.business_name}}</p>
                {% else %}
                  {% if seller.user.profile.is_seller == True and seller.user == request.user %}
                    <a href="{% url 'edit-profile' seller.user.username %}" title="Edit your Business name">Edit profile</a>
                  {% endif %}

                {% endif %}
                  
                
                <p>Joined on <span id="date-joined"> {{ seller.user.date_joined|date:'d F, Y' }} </span></p>
                <img src="{% static 'icons/joined.png' %}" alt="">
              </div>
            </section>


            <!-- MAP -->
            <!-- <section class="our-map"> -->
              <!-- <div class="map-header">
                <h2 class="profile-h2">Map</h2>
              </div> -->
              <!-- <div class="map-details"> -->
                <!-- MAP COMES HERE -->
              <!-- </div> -->
            <!-- </section> -->
          </div>
          <!--END OF PROFILE INFO -->
  
          <!-- PRODUCT & SERVICES -->
          <div class="profile-details-right">
            <section>
              <div id="profile-products" >

                <div class="container product-listing ">
                  <!-- New Upload -->
                  <div class="new-upload ">  
                    <!-- Card -->
                    {% if seller.product_set.all.count > 0 %}
                      <div class="card-wrapper-profile profile-product-details">
                      {% for product in seller.product_set.all %}
                      
                      {% if product.approved %}
                        <div class="card">
                          <div class="card-img">
                            <a href="{% url 'product' product.pk %}"><img src="{{product.image.url}}" alt=""></a>
                          </div>
                          <div class="card-body">
                            <h5 class="product-name">{{ product.name }}</h5>
                            <p class="product-category">{{ product.category.name }}</p>
                            {% if product.previous_price and product.actual_price %}
                            <p class="product-discount">K{{ product.actual_price }}</p>
                            <p class="product-price">K{{ product.previous_price }}</p>
                            {% elif product.actual_price %}
                            <p class="product-discount">K{{ product.actual_price }}</p>
                            {% endif %}
                        
                            <!-- PRODUCT RATES -->
                            {% include '../product_review_rates.html' %}
                          </div>
                          <div class="card-footer">
                            <div class="user-thumnail">
                              <div id="seller-img">
                                <a href="{% url 'profile' product.seller.user.username %}">
                                  <img src="{{ product.seller.image.url }}" alt="seller-img">
                                </a>
                              </div>
                        
                        
                              <span class="seller-name">
                                <a href="{% url 'profile' product.seller.user.username %}">{{ product.seller.user.username.capitalize }}</a>
                              </span>
                            </div>
                        
                            <a href="{% url 'profile' product.seller.user.username %}" class="contact-seller">Contact Seller</a>
                          </div>
                        </div>
                      {% endif %}
                        
                     
    
                      {% endfor %}
                      </div>
                    {% else %}
                      <div>
                        <h1 style="font-size: 3rem; text-align: center; line-height: 1.5;" >
                          WOULD YOU LIKE TO BECOME A 
                          <span style="color: var(--primary-clr);">SELLER?</span> 
                          CONTACT US ON 
                          <span style="color: var(--primary-clr);">(+260-963-319-027)</span>
                        </h1>
                      </div>
                    {% endif %}
                      
                    <!--End of Card -->
                  </div>
                  <!-- End of New Upload -->
          
                </div>
                
              </div>
            </section>
          </div>
          <!-- END OF PRODUCT & SERVICES -->
        </div>
       
      </div>
    </section>



{% endblock %}